//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionLopushock.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class MinCost
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
