//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionLopushock.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movements
    {
        public int Id { get; set; }
        public Nullable<int> CardId { get; set; }
        public string PointArrival { get; set; }
        public Nullable<System.DateTime> DateMovement { get; set; }
    
        public virtual NFCCard NFCCard { get; set; }
    }
}
