//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionLopushock.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Application = new HashSet<Application>();
            this.Change = new HashSet<Change>();
            this.MinCost = new HashSet<MinCost>();
        }
    
        public int Id { get; set; }
        public string Article { get; set; }
        public string Title { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public Nullable<double> Leight { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> WeightNoPack { get; set; }
        public Nullable<double> WeightPack { get; set; }
        public string Certificate { get; set; }
        public Nullable<int> StandardId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application> Application { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Change> Change { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MinCost> MinCost { get; set; }
        public virtual Standard Standard { get; set; }
        public virtual TypeProduct TypeProduct { get; set; }
    }
}
